### ISSUE TITLE
Forgot a table attribute and need to add it but, don't know how?

### ISSUE THREAD

**Issue by jbird33** [jbird33/project3-backend#1]
1) We tried to manually add and then ran npx sequelize db:migrate:all ...   following this site: https://dev.to/nedsoft/add-new-fields-to-existing-sequelize-migration-3527

2) Getting an error that says to install mysql2

**Comment by CRHarding** [comment]
In your config.json file do you have the correct postgres value set for dialect?

"dialect": "postgres",

**Comment by jbird33** [comment]
That fixed the issue. Thank you!

**Comment by davidmagbee** [comment]
Great!
