### ISSUE TITLE
Seeding Issue

### ISSUE THREAD

**Issue by margenta2** [jbird33/project3-backend#2]
1) Getting this error when trying to seed file. Error: null value in column "createdAt" of relation "Users" violates not-null constraint.
2) We've tried to re- migrate. We had to do a secondary migration file because I forgot to add a column to the first migration, but we see the columns all showing now in our database. We tried these resources online: 
[StackOverflow](https://stackoverflow.com/questions/51715526/sequelize-error-null-value-in-column-createdat-violates-not-null-constraint)
[Git Memory](https://www.gitmemory.com/issue/typeorm/typeorm/4838/540116914)
We set a default value for the date, but it's not working.

**Comment by CRHarding** [comment]
You need to add a default value for createdAt and updatedAt in your migration file, look at https://git.generalassemb.ly/cfg-seir-2/Pokemon-Express#create-pokemon-model for a good example.

**Comment by davidmagbee** [comment]
This will also be a helpful resource: [Sequelize Intro](https://git.generalassemb.ly/cfg-seir-2/sequelize-intro)

**Comment by margenta2** [comment]
We did use default value new data before we seeded.
![image](https://user-images.githubusercontent.com/82845203/122111214-147eef00-cde5-11eb-9f97-e90b106beddd.png)

**Comment by CRHarding** [comment]
Did you try and undo the migrations and redo them to make sure the defaultValue is being applied? Sometimes when you change a migration sequelize doesn't think anything changed and just skips over it. I believe the command is `npx sequelize db:migrate:undo:all` and then `npx sequelize db:migrate`

**Comment by margenta2** [comment]
That worked!! Thank you!!!!
